# Generated by Django 3.1.2 on 2020-10-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_id',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_id',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_id',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
