# Generated by Django 3.1.2 on 2020-10-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_details',
            new_name='Product_detail',
        ),
    ]
