# Generated by Django 3.1.2 on 2020-10-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201021_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
